package main

import (
	"fmt"
	"log"
	"strings"
	"unicode"
	"unicode/utf8"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/daotl/protoc-gen-go-enums/pbgen"
)

var includeNested bool

func main() {
	protogen.Options{
		ParamFunc: func(name, value string) error {
			switch name {
			case "include_nested":
				switch value {
				case "true", "yes", "y", "1":
					includeNested = true
				}
			}
			return nil
		},
	}.Run(generate)
}

func generate(gen *protogen.Plugin) error {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		newFileEnumGenerator(f, gen).Generate()
	}
	return nil
}

type fileEnumGenerator struct {
	f   *protogen.File
	gen *protogen.Plugin

	allConsts map[string]struct{}
	gf        *protogen.GeneratedFile
}

func newFileEnumGenerator(f *protogen.File, gen *protogen.Plugin) *fileEnumGenerator {
	gen.SupportedFeatures = gengo.SupportedFeatures
	gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_2023
	gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024

	return &fileEnumGenerator{f: f, gen: gen, allConsts: make(map[string]struct{})}
}

func (eg *fileEnumGenerator) Generate() {
	eg.gf = eg.gen.NewGeneratedFile(eg.f.GeneratedFilenamePrefix+".pb.enums.go", eg.f.GoImportPath)
	eg.writeHeader()

	var seen int
	for _, enum := range eg.f.Enums {
		seen += eg.processEnum(enum)
	}

	if includeNested {
		for _, m := range eg.f.Messages {
			for _, enum := range m.Enums {
				seen += eg.processEnum(enum)
			}
		}
	}

	if seen == 0 {
		// No enums processed
		eg.gf.Skip()
	}
}

func (eg *fileEnumGenerator) writeHeader() {
	eg.gf.P("// Code generated by protoc-gen-go-enums. DO NOT EDIT.")
	eg.gf.P("// source: ", eg.f.Desc.Path())
	eg.gf.P()
	eg.gf.P("package ", eg.f.GoPackageName)
	eg.gf.P()
}

func (eg *fileEnumGenerator) processEnum(enum *protogen.Enum) (seen int) {
	opts, ok := enum.Desc.Options().(*descriptorpb.EnumOptions)
	if !ok {
		log.Fatalf("invalid options type for enum %s", enum.Desc.FullName())
	}

	// If not set, default to true
	if opts != nil && proto.HasExtension(opts, pbgen.E_GenGoEnums) {
		if enabled, ok := proto.GetExtension(opts, pbgen.E_GenGoEnums).(bool); !ok {
			log.Fatalf("invalid type for gen_go_enums option on enum %s", enum.Desc.FullName())
		} else if !enabled {
			return seen
		}
	}

	stripNamePrefix := ""
	if opts != nil && proto.HasExtension(opts, pbgen.E_GenGoEnumsStripNamePrefix) {
		var ok bool
		if stripNamePrefix, ok = proto.GetExtension(opts,
			pbgen.E_GenGoEnumsStripNamePrefix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_strip_name_prefix option on enum %s",
				enum.Desc.FullName(),
			)
		}
	}

	namePascalCase := false
	if opts != nil && proto.HasExtension(opts, pbgen.E_GenGoEnumsNamePascalCase) {
		if npc, ok := proto.GetExtension(opts,
			pbgen.E_GenGoEnumsNamePascalCase).(bool); !ok {
			log.Fatalf(
				"invalid type for gen_go_enums_name_pascal_case option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			namePascalCase = npc
		}
	}

	nameCapsCase := false
	if !namePascalCase && opts != nil && proto.HasExtension(opts, pbgen.E_GenGoEnumsNameCapsCase) {
		if ncc, ok := proto.GetExtension(opts,
			pbgen.E_GenGoEnumsNameCapsCase).(bool); !ok {
			log.Fatalf(
				"invalid type for gen_go_enums_name_pascal_case option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			nameCapsCase = ncc
		}
	}

	namePrefix := ""
	if opts != nil && proto.HasExtension(opts, pbgen.E_GenGoEnumsNamePrefix) {
		if np, ok := proto.GetExtension(opts,
			pbgen.E_GenGoEnumsNamePrefix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_name_prefix option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			namePrefix = np
		}
	}

	nameSuffix := ""
	if opts != nil && proto.HasExtension(opts, pbgen.E_GenGoEnumsNameSuffix) {
		if ns, ok := proto.GetExtension(opts,
			pbgen.E_GenGoEnumsNameSuffix).(string); !ok {
			log.Fatalf(
				"invalid type for gen_go_string_consts_name_suffix option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			nameSuffix = ns
		}
	}

	if hasClash, clashing := eg.hasConstClash(enum, stripNamePrefix, namePascalCase,
		nameCapsCase, namePrefix, nameSuffix); hasClash {
		println(fmt.Sprintf("skipped generating constants for enum %v as it would duplicate constant %s", enum.Desc.FullName(), clashing))
		return seen
	}

	eg.gf.P("const (")
	for _, v := range enum.Values {
		name := eg.constNameFor(v, stripNamePrefix, namePascalCase, nameCapsCase, namePrefix, nameSuffix)
		eg.allConsts[name] = struct{}{}
		if v.Desc.Options().(*descriptorpb.EnumValueOptions).GetDeprecated() {
			eg.gf.P("// Deprecated: Do not use.")
		}
		eg.gf.P(name, " = ", eg.golangValue(v))

		seen++
	}
	eg.gf.P(")")
	eg.gf.P()

	return seen
}

func (eg *fileEnumGenerator) hasConstClash(
	enum *protogen.Enum,
	stripNamePrefix string,
	namePascalCase bool,
	nameCapsCase bool,
	namePrefix,
	nameSuffix string,
) (bool, string) {
	for _, v := range enum.Values {
		constName := eg.constNameFor(v, stripNamePrefix, namePascalCase, nameCapsCase, namePrefix, nameSuffix)
		if _, exists := eg.allConsts[constName]; exists {
			return true, constName
		}
	}
	return false, ""
}

func (eg *fileEnumGenerator) constNameFor(v *protogen.EnumValue,
	stripNamePrefix string,
	namePascalCase bool,
	nameCapsCase bool,
	namePrefix,
	nameSuffix string,
) string {
	name := string(eg.golangValue(v)) // "FOO_A"

	name, _ = strings.CutPrefix(name, stripNamePrefix) // "A"
	if namePascalCase {
		name = toPascalCase(name)
	} else if nameCapsCase {
		name = toCapsCase(name)
	}

	return namePrefix + name + nameSuffix // "{PREFIX}A{SUFFIX}"
}

func (eg *fileEnumGenerator) golangValue(e *protogen.EnumValue) string {
	pkg := string(eg.f.Desc.Package())
	typeName := strings.TrimPrefix(string(e.Parent.Desc.FullName()), ".")
	typeName = strings.TrimPrefix(typeName, pkg+".")

	parts := strings.Split(typeName, ".")
	if len(parts) > 1 {
		typeName = strings.Join(parts[0:len(parts)-1], "_")
	} else {
		typeName = parts[0]
	}

	return typeName + "_" + string(e.Desc.Name())
}

// toPascalCase converts string to PascalCase.
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	if len(parts) == 1 {
		return toPascalCasePart(parts[0])
	}
	result := ""
	for i := range parts {
		if parts[i] != "" {
			result += toPascalCasePart(parts[i])
		}
	}
	return result
}

func toPascalCasePart(s string) string {
	var titleCaser cases.Caser
	// If "ALLCAPS" convert to "Allcaps", if "camelCase" convert to "CamelCase"
	if NoLowercaseASCII(s) {
		titleCaser = cases.Title(language.English)
	} else {
		titleCaser = cases.Title(language.English, cases.NoLower)
	}
	return titleCaser.String(s)
}

func NoLowercaseASCII(s string) bool {
	return !strings.ContainsAny(s, "abcdefghijklmnopqrstuvwxyz")
}

// toCapsCase converts strings like "camelCase_PascalCase_CAPS" to "CAMEL_CASE_PASCAL_CASE_CAPS"
func toCapsCase(s string) string {
	// First, split by underscores
	parts := strings.Split(s, "_")
	result := make([]string, 0, len(parts))

	for _, part := range parts {
		if part == "" {
			continue
		}

		// Convert each part to uppercase
		// Handle camelCase by inserting underscores before uppercase letters
		var capsPart strings.Builder
		for i, r := range part {
			// Only insert underscore before uppercase letter if the previous character was lowercase
			// This prevents adding underscores between consecutive uppercase letters
			if i > 0 && unicode.IsUpper(r) && i < len(part) {
				prevRune, _ := utf8.DecodeRuneInString(part[i-1:])
				if unicode.IsLower(prevRune) {
					capsPart.WriteRune('_')
				}
			}
			capsPart.WriteRune(unicode.ToUpper(r))
		}
		result = append(result, capsPart.String())
	}

	return strings.Join(result, "_")
}
