package main

import (
	"fmt"
	"log"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	gengo "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/daotl/protoc-gen-go-enums/pbgen"
)

var includeNested bool

func main() {
	protogen.Options{
		ParamFunc: func(name, value string) error {
			switch name {
			case "include_nested":
				switch value {
				case "true", "yes", "y", "1":
					includeNested = true
				}
			}
			return nil
		},
	}.Run(generate)
}

func generate(gen *protogen.Plugin) error {
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		newFileEnumGenerator(f, gen).Generate()
	}
	return nil
}

type fileEnumGenerator struct {
	f   *protogen.File
	gen *protogen.Plugin

	allConsts map[string]struct{}
	gf        *protogen.GeneratedFile
}

func newFileEnumGenerator(f *protogen.File, gen *protogen.Plugin) *fileEnumGenerator {
	gen.SupportedFeatures = gengo.SupportedFeatures
	gen.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_2023
	gen.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_2024

	return &fileEnumGenerator{f: f, gen: gen, allConsts: make(map[string]struct{})}
}

func (eg *fileEnumGenerator) Generate() {
	eg.gf = eg.gen.NewGeneratedFile(eg.f.GeneratedFilenamePrefix+".pb.enums.go", eg.f.GoImportPath)
	eg.writeHeader()

	var seen int
	for _, enum := range eg.f.Enums {
		seen += eg.processEnum(enum)
	}

	if includeNested {
		for _, m := range eg.f.Messages {
			for _, enum := range m.Enums {
				seen += eg.processEnum(enum)
			}
		}
	}

	if seen == 0 {
		// No enums processed
		eg.gf.Skip()
	}
}

func (eg *fileEnumGenerator) writeHeader() {
	eg.gf.P("// Code generated by protoc-gen-go-enums. DO NOT EDIT.")
	eg.gf.P("// source: ", eg.f.Desc.Path())
	eg.gf.P()
	eg.gf.P("package ", eg.f.GoPackageName)
	eg.gf.P()
}

func (eg *fileEnumGenerator) processEnum(enum *protogen.Enum) (seen int) {
	opts, ok := enum.Desc.Options().(*descriptorpb.EnumOptions)
	if !ok {
		log.Fatalf("invalid options type for enum %s", enum.Desc.FullName())
	}
	if opts == nil {
		return seen
	}

	// If not set, default to true
	if proto.HasExtension(opts, pbgen.E_GenGoEnums) {
		if enabled, ok := proto.GetExtension(opts, pbgen.E_GenGoEnums).(bool); !ok {
			log.Fatalf("invalid type for gen_go_enums option on enum %s", enum.Desc.FullName())
		} else if !enabled {
			return seen
		}
	}

	namePascalCase := false
	if proto.HasExtension(opts, pbgen.E_GenGoEnumsNamePascalCase) {
		if ncc, ok := proto.GetExtension(opts,
			pbgen.E_GenGoEnumsNamePascalCase).(bool); !ok {
			log.Fatalf(
				"invalid type for gen_go_enums_name_pascal_case option on enum %s",
				enum.Desc.FullName(),
			)
		} else {
			namePascalCase = ncc
		}
	}

	if hasClash, clashing := eg.hasConstClash(enum); hasClash {
		println(fmt.Sprintf("skipped generating constants for enum %v as it would duplicate constant %s", enum.Desc.FullName(), clashing))
		return seen
	}

	eg.gf.P("const (")
	for _, v := range enum.Values {
		c := constNameFor(v, namePascalCase)
		eg.allConsts[c] = struct{}{}
		if v.Desc.Options().(*descriptorpb.EnumValueOptions).GetDeprecated() {
			eg.gf.P("// Deprecated: Do not use.")
		}
		eg.gf.P(c, " = ", eg.golangValue(v))

		seen++
	}
	eg.gf.P(")")
	eg.gf.P()

	return seen
}

func (eg *fileEnumGenerator) hasConstClash(enum *protogen.Enum) (bool, string) {
	for _, v := range enum.Values {
		constName := constNameFor(v, false)
		if _, exists := eg.allConsts[constName]; exists {
			return true, constName
		}
	}
	return false, ""
}

func constNameFor(v *protogen.EnumValue, namePascalCase bool) string {
	name := string(v.Desc.Name())
	if namePascalCase {
		name = snakeToPascalCase(name)
	}
	return name
}

func (eg *fileEnumGenerator) golangValue(e *protogen.EnumValue) string {
	pkg := string(eg.f.Desc.Package())
	typeName := strings.TrimPrefix(string(e.Parent.Desc.FullName()), ".")
	typeName = strings.TrimPrefix(typeName, pkg+".")

	parts := strings.Split(typeName, ".")
	if len(parts) > 1 {
		typeName = strings.Join(parts[0:len(parts)-1], "_")
	} else {
		typeName = parts[0]
	}

	return typeName + "_" + string(e.Desc.Name())
}

// snakeToPascalCase converts a snake_case string to PascalCase.
func snakeToPascalCase(s string) string {
	parts := strings.Split(s, "_")
	titleCaser := cases.Title(language.English)
	if len(parts) == 1 {
		return titleCaser.String(parts[0])
	}
	result := ""
	for i := range parts {
		if parts[i] != "" {
			result += titleCaser.String(parts[i])
		}
	}
	return result
}
