// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: example.proto

package uint32

import (
	_ "github.com/daotl/protoc-gen-go-enums/pbgen"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCode int32

const (
	OpCode_OP_CODE_RESERVED OpCode = 0
	OpCode_OP_CODE_START    OpCode = 1
	OpCode_OP_CODE_STOP     OpCode = 2
	OpCode_OP_CODE_PAUSE    OpCode = 3
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_CODE_RESERVED",
		1: "OP_CODE_START",
		2: "OP_CODE_STOP",
		3: "OP_CODE_PAUSE",
	}
	OpCode_value = map[string]int32{
		"OP_CODE_RESERVED": 0,
		"OP_CODE_START":    1,
		"OP_CODE_STOP":     2,
		"OP_CODE_PAUSE":    3,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\x06uint32\x1a#daotl/protoc-gen-go-enums/ext.proto*g\n" +
	"\x06OpCode\x12\x14\n" +
	"\x10OP_CODE_RESERVED\x10\x00\x12\x11\n" +
	"\rOP_CODE_START\x10\x01\x12\x10\n" +
	"\fOP_CODE_STOP\x10\x02\x12\x11\n" +
	"\rOP_CODE_PAUSE\x10\x03\x1a\x0f\xca\xe4,\aOpCode_\xf0\xe4,\x01B5Z3github.com/daotl/protoc-gen-go-enums/example/uint32b\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_proto_goTypes = []any{
	(OpCode)(0), // 0: uint32.OpCode
}
var file_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
