// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: example.proto

package uint32

const (
	OP_CODE_RESERVED = uint32(OpCode_OP_CODE_RESERVED)
	OP_CODE_START    = uint32(OpCode_OP_CODE_START)
	OP_CODE_STOP     = uint32(OpCode_OP_CODE_STOP)
	OP_CODE_PAUSE    = uint32(OpCode_OP_CODE_PAUSE)
)
