// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: ext.proto

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         91720,
		Name:          "daotl.proto.gen_go_enums",
		Tag:           "varint,91720,opt,name=gen_go_enums",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         91721,
		Name:          "daotl.proto.gen_go_enums_strip_name_prefix",
		Tag:           "bytes,91721,opt,name=gen_go_enums_strip_name_prefix",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         91722,
		Name:          "daotl.proto.gen_go_enums_name_pascal_case",
		Tag:           "varint,91722,opt,name=gen_go_enums_name_pascal_case",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         91723,
		Name:          "daotl.proto.gen_go_enums_name_caps_case",
		Tag:           "varint,91723,opt,name=gen_go_enums_name_caps_case",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         91724,
		Name:          "daotl.proto.gen_go_enums_name_prefix",
		Tag:           "bytes,91724,opt,name=gen_go_enums_name_prefix",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         91725,
		Name:          "daotl.proto.gen_go_enums_name_suffix",
		Tag:           "bytes,91725,opt,name=gen_go_enums_name_suffix",
		Filename:      "ext.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// Enable generation of renamed Go constants from enums. (Default: true)
	//
	// optional bool gen_go_enums = 91720;
	E_GenGoEnums = &file_ext_proto_extTypes[0]
	// Strip prefix. (Default: true)
	//
	// optional string gen_go_enums_strip_name_prefix = 91721;
	E_GenGoEnumsStripNamePrefix = &file_ext_proto_extTypes[1]
	// Turn const name into pascal case
	// (apply before  `gen_go_enums_name_prefix` and `gen_go_enums_name_suffix`).
	//
	// optional bool gen_go_enums_name_pascal_case = 91722;
	E_GenGoEnumsNamePascalCase = &file_ext_proto_extTypes[2]
	// If true convert string const name into CAPS_CASE
	// (apply before `gen_go_string_consts_name_prefix` and `gen_go_string_consts_name_suffix`).
	// Can't be used together with gen_go_string_consts_name_pascal_case.
	//
	// optional bool gen_go_enums_name_caps_case = 91723;
	E_GenGoEnumsNameCapsCase = &file_ext_proto_extTypes[3]
	// Add string prefix to generated Go string constant names.
	//
	// optional string gen_go_enums_name_prefix = 91724;
	E_GenGoEnumsNamePrefix = &file_ext_proto_extTypes[4]
	// Add string suffix to generated Go string constant names.
	//
	// optional string gen_go_enums_name_suffix = 91725;
	E_GenGoEnumsNameSuffix = &file_ext_proto_extTypes[5]
)

var File_ext_proto protoreflect.FileDescriptor

const file_ext_proto_rawDesc = "" +
	"\n" +
	"\text.proto\x12\vdaotl.proto\x1a google/protobuf/descriptor.proto:@\n" +
	"\fgen_go_enums\x12\x1c.google.protobuf.EnumOptions\x18\xc8\xcc\x05 \x01(\bR\n" +
	"genGoEnums:a\n" +
	"\x1egen_go_enums_strip_name_prefix\x12\x1c.google.protobuf.EnumOptions\x18\xc9\xcc\x05 \x01(\tR\x19genGoEnumsStripNamePrefix:_\n" +
	"\x1dgen_go_enums_name_pascal_case\x12\x1c.google.protobuf.EnumOptions\x18\xca\xcc\x05 \x01(\bR\x18genGoEnumsNamePascalCase:[\n" +
	"\x1bgen_go_enums_name_caps_case\x12\x1c.google.protobuf.EnumOptions\x18\xcb\xcc\x05 \x01(\bR\x16genGoEnumsNameCapsCase:V\n" +
	"\x18gen_go_enums_name_prefix\x12\x1c.google.protobuf.EnumOptions\x18\xcc\xcc\x05 \x01(\tR\x14genGoEnumsNamePrefix:V\n" +
	"\x18gen_go_enums_name_suffix\x12\x1c.google.protobuf.EnumOptions\x18\xcd\xcc\x05 \x01(\tR\x14genGoEnumsNameSuffixB\x94\x01\n" +
	"\x0fcom.daotl.protoB\bExtProtoP\x01Z*github.com/daotl/protoc-gen-go-enums/pbgen\xa2\x02\x03DPX\xaa\x02\vDaotl.Proto\xca\x02\vDaotl\\Proto\xe2\x02\x17Daotl\\Proto\\GPBMetadata\xea\x02\fDaotl::Protob\x06proto3"

var file_ext_proto_goTypes = []any{
	(*descriptorpb.EnumOptions)(nil), // 0: google.protobuf.EnumOptions
}
var file_ext_proto_depIdxs = []int32{
	0, // 0: daotl.proto.gen_go_enums:extendee -> google.protobuf.EnumOptions
	0, // 1: daotl.proto.gen_go_enums_strip_name_prefix:extendee -> google.protobuf.EnumOptions
	0, // 2: daotl.proto.gen_go_enums_name_pascal_case:extendee -> google.protobuf.EnumOptions
	0, // 3: daotl.proto.gen_go_enums_name_caps_case:extendee -> google.protobuf.EnumOptions
	0, // 4: daotl.proto.gen_go_enums_name_prefix:extendee -> google.protobuf.EnumOptions
	0, // 5: daotl.proto.gen_go_enums_name_suffix:extendee -> google.protobuf.EnumOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ext_proto_init() }
func file_ext_proto_init() {
	if File_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ext_proto_rawDesc), len(file_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_ext_proto_goTypes,
		DependencyIndexes: file_ext_proto_depIdxs,
		ExtensionInfos:    file_ext_proto_extTypes,
	}.Build()
	File_ext_proto = out.File
	file_ext_proto_goTypes = nil
	file_ext_proto_depIdxs = nil
}
