// Code generated by protoc-gen-go-enums. DO NOT EDIT.
// source: example.proto

package conflictingenums

const (
	OpCodeReserved            = OpCode_OP_CODE_RESERVED
	OpCodeResolution          = OpCode_OP_CODE_RESOLUTION
	OpCodeGetSiteinfo         = OpCode_OP_CODE_GET_SITEINFO
	OpCodeCreateId            = OpCode_OP_CODE_CREATE_ID
	OpCodeDeleteId            = OpCode_OP_CODE_DELETE_ID
	OpCodeAddElement          = OpCode_OP_CODE_ADD_ELEMENT
	OpCodeRemoveElement       = OpCode_OP_CODE_REMOVE_ELEMENT
	OpCodeModifyElement       = OpCode_OP_CODE_MODIFY_ELEMENT
	OpCodeListIds             = OpCode_OP_CODE_LIST_IDS
	OpCodeListDerivedPrefixes = OpCode_OP_CODE_LIST_DERIVED_PREFIXES
	OpCodeChallengeResponse   = OpCode_OP_CODE_CHALLENGE_RESPONSE
	OpCodeVerifyResponse      = OpCode_OP_CODE_VERIFY_RESPONSE
	OpCodeHomePrefix          = OpCode_OP_CODE_HOME_PREFIX
	OpCodeUnhomePrefix        = OpCode_OP_CODE_UNHOME_PREFIX
	OpCodeListHomedPrefixes   = OpCode_OP_CODE_LIST_HOMED_PREFIXES
	OpCodeSessionSetup        = OpCode_OP_CODE_SESSION_SETUP
	OpCodeSessionTerminate    = OpCode_OP_CODE_SESSION_TERMINATE
)

const (
	SampleMessage1InnerEnumUnknown = SampleMessage1_INNER_ENUM_UNKNOWN
	SampleMessage1InnerEnumVal2    = SampleMessage1_INNER_ENUM_VAL2
)

const (
	SAMPLE_MESSAGE2_INNER_ENUM_UNKNOWN = SampleMessage2_INNER_ENUM_UNKNOWN
	SAMPLE_MESSAGE2_INNER_ENUM_VAL3    = SampleMessage2_INNER_ENUM_VAL3
)
